### ISSUE TITLE
Additional packages required on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by nicorikken** [chaoss/MARS#17]
I'm trying MARS on Ubuntu 18.04 LTS.

Initially I got an error building:

```
...
Copying: wg-value/focus-areas/organizational-value/labor-investment.md
Copied Successfully

Decreasing heading levels by 2 in metric: labor-investment.md
Converting labor-investment.md file to LaTeX
Created successfully: labor-investment.tex

Copying: wg-value/focus-areas/organizational-value/images/labor-investment_csv.png
Copied Successfully

Generating focus-area file = wg-value_organizational-value.tex

Converting master.tex file to PDF
Traceback (most recent call last):
  File "main.py", line 327, in <module>
    main()
  File "main.py", line 321, in main
    convert_tex2pdf(master_file_path, output_filename)
  File "main.py", line 65, in convert_tex2pdf
    output = pypandoc.convert_file(tex_filename, 'pdf', outputfile=pdf_filename, extra_args=['-f', 'latex',
  File "/home/nico/Software/chaoss/MARS/automation-english/.venv/lib/python3.8/site-packages/pypandoc/__init__.py", line 137, in convert_file
    return _convert_input(source_file, format, 'path', to, extra_args=extra_args,
  File "/home/nico/Software/chaoss/MARS/automation-english/.venv/lib/python3.8/site-packages/pypandoc/__init__.py", line 321, in _convert_input
    raise RuntimeError(
RuntimeError: Pandoc died with exitcode "43" during conversion: b"Error producing PDF.\n! LaTeX Error: File `libertine.sty' not found.\n\nType X to quit or <RETURN> to proceed,\nor enter new name. (Default extension: sty)\n\nEnter file name: \n! Emergency stop.\n<read *> \n         \nl.3 \\usepackage\n\n"
```

Turns out I needed to install an additional package:

```
sudo apt install texlive-fonts-extra
```

Then I got another error:
```
...
Decreasing heading levels by 2 in metric: labor-investment.md
Converting labor-investment.md file to LaTeX
Created successfully: labor-investment.tex

Copying: wg-value/focus-areas/organizational-value/images/labor-investment_csv.png
Copied Successfully

Generating focus-area file = wg-value_organizational-value.tex

Converting master.tex file to PDF
    main()
  File "main.py", line 321, in main
    convert_tex2pdf(master_file_path, output_filename)
  File "main.py", line 65, in convert_tex2pdf
    output = pypandoc.convert_file(tex_filename, 'pdf', outputfile=pdf_filename, extra_args=['-f', 'latex',
  File "/home/nico/Software/chaoss/MARS/automation-english/.venv/lib/python3.8/site-packages/pypandoc/__init__.py", line 137, in convert_file
    return _convert_input(source_file, format, 'path', to, extra_args=extra_args,
  File "/home/nico/Software/chaoss/MARS/automation-english/.venv/lib/python3.8/site-packages/pypandoc/__init__.py", line 321, in _convert_input
    raise RuntimeError(
RuntimeError: Pandoc died with exitcode "43" during conversion: b'Error producing PDF.\n! LaTeX Error: Option clash for package fontspec.\n\nSee the LaTeX manual or LaTeX Companion for explanation.\nType  H <return>  for immediate help.\n ...                                              \n                                                  \nl.65 ...Package[\\eu@zf@math]{fontspec}[2008/08/09]\n\n'
```

That seems to have something to do with multiple requirements, [according to the LaTeX documentation](https://nuanceabounds.org/fix-latex-package-option-clash-error-passoptionstopackage/).

Perhaps because I already installed multiple packages having something to do with fontspec?

```
apt search fontspec
Sorting... Done
Full Text Search... Done
texlive-fonts-extra/focal,focal,now 2019.202000218-1 all [installed]
  TeX Live: Additional fonts

texlive-latex-extra/focal,focal,now 2019.202000218-1 all [installed,automatic]
  TeX Live: LaTeX additional packages

texlive-latex-recommended/focal,focal,now 2019.20200218-1 all [installed,automatic]
  TeX Live: LaTeX recommended packages
```

I'm now looking into the documentation of [pypandoc](https://github.com/NicklasTegner/pypandoc)

**Comment by ritik-malik** [comment]
This is weird,
Can you crosscheck you dependencies from our Docker image hosted [here](https://hub.docker.com/r/ritikmalik/mars-image)?
The README on this link contains all the packages required and it is working fine with that.
We are using `ubuntu:latest` as our base image.

**Comment by nicorikken** [comment]
Yeah, I can see this being a version issue between the latest Ubuntu 21.04 and my 20.04. For reference:
```
$ apt list git gosu curl wget texlive-xetex pandoc ttf-mscorefonts-installer python3-pip texlive-fonts-extra
Listing... Done
curl/focal-updates,focal-security,now 7.68.0-1ubuntu2.5 amd64 [installed]
curl/focal-updates,focal-security 7.68.0-1ubuntu2.5 i386
git/focal-updates,focal-security,now 1:2.25.1-1ubuntu3.1 amd64 [installed]
git/focal-updates,focal-security 1:2.25.1-1ubuntu3.1 i386
gosu/focal-updates 1.10-1ubuntu0.20.04.1 amd64
pandoc/focal,now 2.5-3build2 amd64 [installed]
python3-pip/focal-updates,focal-updates,focal-security,focal-security,now 20.0.2-5ubuntu1.5 all [installed]
texlive-fonts-extra/focal,focal,now 2019.202000218-1 all [installed]
texlive-xetex/focal,focal,now 2019.20200218-1 all [installed]
ttf-mscorefonts-installer/focal,focal,now 3.7ubuntu6 all [installed]
wget/focal,now 1.20.3-1ubuntu1 amd64 [installed]
wget/focal 1.20.3-1ubuntu1 i386
```

**Comment by ritik-malik** [comment]
Hi @nicorikken , are you able to resolve this issue now (considering the new changes in MARS)?

**Comment by nicorikken** [comment]
@ritik-malik what changes are you referring to? I see no changes in docs or requirements on this part. I tried it again and end up with the same error. With Docker as an available option, it could be a decision not to support 18.04 LTS and close this issue.

**Comment by ritik-malik** [comment]
Can you specify your system specs? In the issue heading it says `Ubuntu 18.04 LTS` while in [this](https://github.com/chaoss/MARS/issues/17#issuecomment-883606075) comment it says `20.04`.
Also, I can see `i386` in your output. Could it be anything to do with support issues in 32 bit machines?

This is most likely a font issue. Did you acccept the EULA during the installation of `ttf-mscorefonts-installer`?

**Comment by nicorikken** [comment]
It was Ubuntu 20.04. I enforced the EULA accept prompt by first purging the package and then installing it again. I still get the same error.

**Comment by ritik-malik** [comment]
In the error it says - `Error producing PDF.\n! LaTeX Error: Option clash for package fontspec`
Can you try after uninstalling this package: `texlive-fonts-extra`.

**Comment by nicorikken** [comment]
Alright, let's persist then:
```
$ sudo apt remove texlive-fonts-extra
$ python main.py
...
Generating focus-area file = wg-value_organizational-value.tex

Converting master.tex file to PDF
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    main()
  File "main.py", line 73, in main
    metrics_release.release_main("english")
  File "/home/nico/Software/chaoss/MARS/automation/metrics_release.py", line 159, in release_main
    pdf_filename = helper.convert_tex2pdf(main.master_file_path, word_translation_yaml_data, language, cover_filename)
  File "/home/nico/Software/chaoss/MARS/automation/helper.py", line 388, in convert_tex2pdf
    output = pypandoc.convert_file(tex_filename, 'pdf', outputfile=pdf_filename, extra_args=['-f', 'latex',
  File "/home/nico/Software/chaoss/MARS/.venv/lib/python3.8/site-packages/pypandoc/__init__.py", line 137, in convert_file
    return _convert_input(source_file, format, 'path', to, extra_args=extra_args,
  File "/home/nico/Software/chaoss/MARS/.venv/lib/python3.8/site-packages/pypandoc/__init__.py", line 321, in _convert_input
    raise RuntimeError(
RuntimeError: Pandoc died with exitcode "43" during conversion: b"Error producing PDF.\n! LaTeX Error: File `libertine.sty' not found.\n\nType X to quit or <RETURN> to proceed,\nor enter new name. (Default extension: sty)\n\nEnter file name: \n! Emergency stop.\n<read *> \n         \nl.3 \\usepackage\n\n"

$ sudo apt install -y git wget texlive-xetex pandoc python3-pip python3-venv texlive-lang-chinese ttf-mscorefonts-installer

$ python main.py
 ... (same error)

$ kpsewhich libertine.sty
(nothing)

$ apt search libertine
Sorting... Done
Full Text Search... Done
fonts-linuxlibertine/focal,focal,now 5.3.0-4 all [installed,automatic]
  Linux Libertine family of fonts

texlive-fonts-extra/focal,focal 2019.202000218-1 all
  TeX Live: Additional fonts

texlive-latex-extra/focal,focal,now 2019.202000218-1 all [installed]
  TeX Live: LaTeX additional packages

$ sudo apt purge texlive-latex-extra

$ python main.py
...
Generating focus-area file = wg-value_organizational-value.tex

Converting master.tex file to PDF
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    main()
  File "main.py", line 73, in main
    metrics_release.release_main("english")
  File "/home/nico/Software/chaoss/MARS/automation/metrics_release.py", line 159, in release_main
    pdf_filename = helper.convert_tex2pdf(main.master_file_path, word_translation_yaml_data, language, cover_filename)
  File "/home/nico/Software/chaoss/MARS/automation/helper.py", line 388, in convert_tex2pdf
    output = pypandoc.convert_file(tex_filename, 'pdf', outputfile=pdf_filename, extra_args=['-f', 'latex',
  File "/home/nico/Software/chaoss/MARS/.venv/lib/python3.8/site-packages/pypandoc/__init__.py", line 137, in convert_file
    return _convert_input(source_file, format, 'path', to, extra_args=extra_args,
  File "/home/nico/Software/chaoss/MARS/.venv/lib/python3.8/site-packages/pypandoc/__init__.py", line 321, in _convert_input
    raise RuntimeError(
RuntimeError: Pandoc died with exitcode "47" during conversion: b'xelatex not found. Please select a different --pdf-engine or install xelatex -- see also /usr/share/doc/pandoc/README.Debian\n'

$ cat /usr/share/doc/pandoc/README.Debian
# Notes about Debian packaging of Pandoc

## Packages needed for optional features

Some uses of Pandoc require additional packages:

  * SVG content in PDF output requires librsvg2-bin.
  * YAML metadata in TeX-related output requires texlive-latex-extra.
  * *.hs filters not set executable requires ghc.
  * *.js filters not set executable requires nodejs.
  * *.php filters not set executable requires php.
  * *.pl filters not set executable requires perl.
  * *.py filters not set executable requires python.
  * *.rb filters not set executable requires ruby.
  * *.r filters not set executable requires r-base-core.
  * LaTeX output, and PDF output via PDFLaTeX,
    require texlive-latex-recommended.
  * XeLaTeX output, and PDF output via XeLaTeX, require texlive-xetex.
  * LuaTeX output, and PDF output via LuaTeX, require texlive-luatex.
  * ConTeXt output, and PDF output via ConTeXt, require context.
  * PDF output via wkhtmltopdf requires wkhtmltopdf.
  * Roff man and roff ms output, and PDF output via roff ms,
    require groff.
  * MathJax-rendered equations require libjs-mathjax.
  * KaTeX-rendered equations require node-katex.


## Standalone output not always fully standalone

Some output formats depend on external material,
e.g. Javascript code for rendering mathematical equations.

Pandoc commonly links to such external material hosted on a public CDN.
Due to concerns for potential breach of privacy,
Debian-packaged Pandoc instead links to locally packaged material.

$  dpkg-query -l texlive-xetex
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
un  texlive-xetex  <none>       <none>       (no description available)

$ sudo apt install texlive-xetex

$ python main.py
...
Generating focus-area file = wg-value_organizational-value.tex

Converting master.tex file to PDF
Traceback (most recent call last):
  File "main.py", line 109, in <module>
    main()
  File "main.py", line 73, in main
    metrics_release.release_main("english")
  File "/home/nico/Software/chaoss/MARS/automation/metrics_release.py", line 159, in release_main
    pdf_filename = helper.convert_tex2pdf(main.master_file_path, word_translation_yaml_data, language, cover_filename)
  File "/home/nico/Software/chaoss/MARS/automation/helper.py", line 388, in convert_tex2pdf
    output = pypandoc.convert_file(tex_filename, 'pdf', outputfile=pdf_filename, extra_args=['-f', 'latex',
  File "/home/nico/Software/chaoss/MARS/.venv/lib/python3.8/site-packages/pypandoc/__init__.py", line 137, in convert_file
    return _convert_input(source_file, format, 'path', to, extra_args=extra_args,
  File "/home/nico/Software/chaoss/MARS/.venv/lib/python3.8/site-packages/pypandoc/__init__.py", line 321, in _convert_input
    raise RuntimeError(
RuntimeError: Pandoc died with exitcode "43" during conversion: b"Error producing PDF.\n! LaTeX Error: File `libertine.sty' not found.\n\nType X to quit or <RETURN> to proceed,\nor enter new name. (Default extension: sty)\n\nEnter file name: \n! Emergency stop.\n<read *> \n         \nl.3 \\usepackage\n\n"
```

Not sure how to go from here.

**Comment by ritik-malik** [comment]
Have you updated TeX with this newly installed font? Refer to https://tex.stackexchange.com/a/353604
